name: foodie
description: A simple restaurant app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-56.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  flutter_hooks: ^0.20.0
  dio: ^5.0.1
  get_it: ^7.6.0
  flutter_smart_dialog: ^4.9.3+2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.14
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.15
  carousel_slider: ^4.2.1
  badges: ^3.1.1
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  flutter_svg_provider: ^1.0.4
  awesome_dialog: ^3.1.0
  grouped_list: ^5.1.2
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0' 

  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: images/logo1.png
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  image: images/logo.png
  color: "#f5f5f5"

flutter:


  uses-material-design: true


  assets:
    - images/
    - images/svg/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
